from __future__ import annotations

from dataclasses import dataclass, field
from enum import StrEnum
from typing import Any


class AlignmentStatus(StrEnum):
    NOT_STARTED = "not_started"
    IN_PROGRESS = "in_progress"
    COMPLETE = "complete"


@dataclass
class ControlPoint:
    """A warp control point in working-resolution pixel coordinates.

    src_* : pixel position in atlas overlay space — fixed when the point is
            created; identifies which atlas feature is being moved.
    dst_* : pixel position in section image space — updated as the user drags
            the point to indicate where the feature should appear.
    auto  : True when the point was generated by the automatic (elastix)
            registration rather than placed by hand. Auto points are discarded
            and recreated on every auto-registration run; manual points persist.
    """

    src_x: float
    src_y: float
    dst_x: float
    dst_y: float
    auto: bool = False

    def to_dict(self) -> dict[str, float]:
        d: dict[str, Any] = {
            "src_x": self.src_x,
            "src_y": self.src_y,
            "dst_x": self.dst_x,
            "dst_y": self.dst_y,
        }
        # Only emit when set, so legacy/manual-only projects keep identical JSON.
        if self.auto:
            d["auto"] = True
        return d

    @classmethod
    def from_dict(cls, d: dict[str, Any]) -> ControlPoint:
        return cls(
            src_x=d["src_x"],
            src_y=d["src_y"],
            dst_x=d["dst_x"],
            dst_y=d["dst_y"],
            auto=bool(d.get("auto", False)),
        )


@dataclass
class Alignment:
    """Affine registration of a section to the atlas.

    anchoring: 9-element list [ox, oy, oz, ux, uy, uz, vx, vy, vz]
        o = origin corner of the section plane in atlas voxel space
        u = right direction vector (along section width, unnormalized)
        v = down direction vector (along section height, unnormalized)

    For a point at normalized coords (s, t) ∈ [0, 1]²:
        atlas_voxel = o + s·u + t·v

    This matches the QuickNII anchoring format exactly.
    """

    anchoring: list[float] = field(default_factory=lambda: [0.0] * 9)
    position_mm: float | None = None
    status: AlignmentStatus = AlignmentStatus.NOT_STARTED
    source: str | None = None
    stored_anchoring: list[float] | None = None
    proposal_anchoring: list[float] | None = None
    proposal_confidence: float | None = None
    proposal_run_id: str | None = None

    def __post_init__(self) -> None:
        if (
            self.status == AlignmentStatus.COMPLETE
            and self.stored_anchoring is None
            and self.anchoring
            and any(v != 0.0 for v in self.anchoring)
        ):
            self.stored_anchoring = list(self.anchoring)

    def set_auto_proposal(
        self,
        anchoring: list[float],
        *,
        source: str,
        proposal_anchoring: list[float] | None = None,
        confidence: float | None = None,
        run_id: str | None = None,
    ) -> None:
        """Reset this alignment to an automatically-generated IN_PROGRESS proposal.

        Drops all saved/derived plane state (the stored anchoring and the
        derived ``position_mm``) so the alignment is entirely the fresh guess,
        and records the proposal provenance. Callers typically follow with
        :meth:`WarpState.reset` since the plane moved.

        Args:
            anchoring: The propagated 9-value anchoring to adopt as live.
            source: Provenance tag for the guess (e.g. ``"deepslice"``,
                ``"quicknii_default"``).
            proposal_anchoring: Optional automated-proposal anchoring to record;
                ``None`` clears any previous proposal.
            confidence: Optional proposal confidence.
            run_id: Optional id of the run that produced the proposal.
        """
        self.anchoring = anchoring
        self.position_mm = None
        self.status = AlignmentStatus.IN_PROGRESS
        self.source = source
        self.stored_anchoring = None
        self.proposal_anchoring = proposal_anchoring
        self.proposal_confidence = confidence
        self.proposal_run_id = run_id

    def to_dict(self) -> dict[str, Any]:
        data = {
            "anchoring": self.anchoring,
            "position_mm": self.position_mm,
            "status": self.status.value,
        }
        if self.source is not None:
            data["source"] = self.source
        if self.stored_anchoring is not None:
            data["stored_anchoring"] = self.stored_anchoring
        if self.proposal_anchoring is not None:
            data["proposal_anchoring"] = self.proposal_anchoring
        if self.proposal_confidence is not None:
            data["proposal_confidence"] = self.proposal_confidence
        if self.proposal_run_id is not None:
            data["proposal_run_id"] = self.proposal_run_id
        return data

    @classmethod
    def from_dict(cls, d: dict[str, Any]) -> Alignment:
        return cls(
            anchoring=d.get("anchoring", [0.0] * 9),
            position_mm=d.get("position_mm", d.get("ap_position_mm")),
            status=AlignmentStatus(d.get("status", "not_started")),
            source=d.get("source"),
            stored_anchoring=d.get("stored_anchoring"),
            proposal_anchoring=d.get("proposal_anchoring"),
            proposal_confidence=d.get("proposal_confidence"),
            proposal_run_id=d.get("proposal_run_id"),
        )


@dataclass
class WarpState:
    """Nonlinear warp refinement state for one section."""

    control_points: list[ControlPoint] = field(default_factory=list)
    status: AlignmentStatus = AlignmentStatus.NOT_STARTED

    def reset(self) -> None:
        """Discard all warp refinement, returning to the un-warped affine state."""
        self.control_points.clear()
        self.status = AlignmentStatus.NOT_STARTED

    def to_dict(self) -> dict[str, Any]:
        return {
            "control_points": [cp.to_dict() for cp in self.control_points],
            "status": self.status.value,
        }

    @classmethod
    def from_dict(cls, d: dict[str, Any]) -> WarpState:
        cps = [ControlPoint.from_dict(cp) for cp in d.get("control_points", [])]
        return cls(
            control_points=cps,
            status=AlignmentStatus(d.get("status", "not_started")),
        )
