from __future__ import annotations

from dataclasses import dataclass, field
from enum import StrEnum
from typing import Any

from verso.engine.anchoring.core import is_anchored


class AlignmentStatus(StrEnum):
    NOT_STARTED = "not_started"
    IN_PROGRESS = "in_progress"
    COMPLETE = "complete"


@dataclass
class ControlPoint:
    """A warp control point in working-resolution pixel coordinates.

    src_* : pixel position in atlas overlay space — fixed when the point is
            created; identifies which atlas feature is being moved.
    dst_* : pixel position in section image space — updated as the user drags
            the point to indicate where the feature should appear.
    auto  : True when the point was generated by the automatic (elastix)
            registration rather than placed by hand. Auto points are discarded
            and recreated on every auto-registration run; manual points persist.
    """

    src_x: float
    src_y: float
    dst_x: float
    dst_y: float
    auto: bool = False

    def to_dict(self) -> dict[str, float]:
        d: dict[str, Any] = {
            "src_x": self.src_x,
            "src_y": self.src_y,
            "dst_x": self.dst_x,
            "dst_y": self.dst_y,
        }
        # Only emit when set, so legacy/manual-only projects keep identical JSON.
        if self.auto:
            d["auto"] = True
        return d

    @classmethod
    def from_dict(cls, d: dict[str, Any]) -> ControlPoint:
        return cls(
            src_x=d["src_x"],
            src_y=d["src_y"],
            dst_x=d["dst_x"],
            dst_y=d["dst_y"],
            auto=bool(d.get("auto", False)),
        )


@dataclass
class Alignment:
    """Affine registration of a section to the atlas.

    A plane is a 9-element anchoring vector [ox, oy, oz, ux, uy, uz, vx, vy, vz]:
        o = origin corner of the section plane in atlas voxel space
        u = right direction vector (along section width, unnormalized)
        v = down direction vector (along section height, unnormalized)

    For a point at normalized coords (s, t) ∈ [0, 1]²:
        atlas_voxel = o + s·u + t·v

    This matches the QuickNII anchoring format exactly.

    Two planes are held:

    - ``stored_anchoring`` — the **saved** plane; the single source of truth and
      the only one persisted (as ``"anchoring"`` in JSON). Set on commit.
    - ``current_anchoring`` — the **live** working copy, mutated during editing
      and seeded from ``stored_anchoring`` on load. Transient; never persisted.

    ``position_mm`` is a derived display cache (not persisted).
    """

    current_anchoring: list[float] = field(default_factory=lambda: [0.0] * 9)
    position_mm: float | None = None
    status: AlignmentStatus = AlignmentStatus.NOT_STARTED
    source: str | None = None
    stored_anchoring: list[float] | None = None

    def __post_init__(self) -> None:
        if (
            self.status == AlignmentStatus.COMPLETE
            and self.stored_anchoring is None
            and is_anchored(self.current_anchoring)
        ):
            self.stored_anchoring = list(self.current_anchoring)

    @property
    def is_anchored(self) -> bool:
        """True when the live working plane is a real (non-zero) plane.

        Checks ``current_anchoring`` on purpose — this answers "does the section
        have any plane at all, saved or in-progress" (used for UI enablement and
        ``has_alignment`` checks). Export/interpolation read ``stored_anchoring``
        instead, so only saved planes reach them.
        """
        return is_anchored(self.current_anchoring)

    def set_auto_proposal(self, anchoring: list[float], *, source: str) -> None:
        """Reset this alignment to an automatically-generated IN_PROGRESS proposal.

        Drops all saved/derived plane state (the stored anchoring and the
        derived ``position_mm``) so the alignment is entirely the fresh guess.
        Callers typically follow with :meth:`WarpState.reset` since the plane
        moved.

        Args:
            anchoring: The propagated 9-value anchoring to adopt as the live plane.
            source: Provenance tag for the guess (e.g. ``"deepslice"``,
                ``"series_interpolation"``).
        """
        self.current_anchoring = anchoring
        self.position_mm = None
        self.status = AlignmentStatus.IN_PROGRESS
        self.source = source
        self.stored_anchoring = None

    def to_dict(self) -> dict[str, Any]:
        # Only the saved plane is persisted, under the canonical key "anchoring".
        # The live working copy and position_mm are derived, so they are dropped.
        data: dict[str, Any] = {"status": self.status.value}
        if self.source is not None:
            data["source"] = self.source
        if self.stored_anchoring is not None:
            data["anchoring"] = self.stored_anchoring
        return data

    @classmethod
    def from_dict(cls, d: dict[str, Any]) -> Alignment:
        # "anchoring" is the single persisted (saved) plane; the live working
        # copy is seeded from it and position_mm is recomputed, so neither is
        # read from disk.
        stored = d.get("anchoring")
        return cls(
            current_anchoring=list(stored) if stored is not None else [0.0] * 9,
            status=AlignmentStatus(d.get("status", "not_started")),
            source=d.get("source"),
            stored_anchoring=stored,
        )


@dataclass
class WarpState:
    """Nonlinear warp refinement state for one section."""

    control_points: list[ControlPoint] = field(default_factory=list)
    status: AlignmentStatus = AlignmentStatus.NOT_STARTED

    def reset(self) -> None:
        """Discard all warp refinement, returning to the un-warped affine state."""
        self.control_points.clear()
        self.status = AlignmentStatus.NOT_STARTED

    def to_dict(self) -> dict[str, Any]:
        return {
            "control_points": [cp.to_dict() for cp in self.control_points],
            "status": self.status.value,
        }

    @classmethod
    def from_dict(cls, d: dict[str, Any]) -> WarpState:
        cps = [ControlPoint.from_dict(cp) for cp in d.get("control_points", [])]
        return cls(
            control_points=cps,
            status=AlignmentStatus(d.get("status", "not_started")),
        )
