classdef tParity < matlab.unittest.TestCase
    %TPARITY Cross-language numerical parity against the Python golden fixture.
    %   Reads matlab/tests/fixtures/parity.json -- generated by the Python
    %   engine (tests/engine/test_matlab_parity.py) -- and asserts the MATLAB
    %   port reproduces the same outputs for the same inputs. JSON is the
    %   language-neutral contract boundary: this test never runs Python.
    %
    %   The Python side has its own test asserting the live engine still equals
    %   the committed fixture, so `python == fixture` and `matlab == fixture`
    %   together give `python == matlab`.
    %
    %   Regenerate the fixture after an intentional numeric change with
    %   `UPDATE_PARITY_FIXTURES=1 uv run pytest tests/engine/test_matlab_parity.py`,
    %   then re-run this suite and commit the JSON.
    %
    %   Run with: runtests('matlab/tests')

    properties
        Cases
        Tol
        FixturesDir
    end

    methods (TestClassSetup)
        function loadFixture(testCase)
            here = fileparts(mfilename("fullpath"));
            testCase.FixturesDir = fullfile(here, "fixtures");
            raw = fileread(fullfile(testCase.FixturesDir, "parity.json"));
            testCase.Cases = jsondecode(raw);
            testCase.Tol = testCase.Cases.tolerance;
        end
    end

    methods (Test)
        function warpSectionToAtlas(testCase)
            testCase.checkWarp(testCase.Cases.warp_section_to_atlas, ...
                @verso.VersoRegistration.warpSectionToAtlasForTesting);
        end

        function warpAtlasToSection(testCase)
            testCase.checkWarp(testCase.Cases.warp_atlas_to_section, ...
                @verso.VersoRegistration.warpAtlasToSectionForTesting);
        end

        function anchoringToVectors(testCase)
            cases = testCase.Cases.anchoring_to_vectors;
            for k = 1:numel(cases)
                c = cases(k);
                ouv = verso.VersoRegistration.anchoringVectorsForTesting(c.anchoring);
                testCase.verifyEqual(ouv, c.ouv, "AbsTol", testCase.Tol, c.name);
            end
        end

        function quickniiVoxelIndices(testCase)
            cases = testCase.Cases.quicknii_voxel_indices;
            for k = 1:numel(cases)
                c = cases(k);
                idx = verso.VersoRegistration.quickniiVoxelIndicesForTesting(c.coords_lr_ap_dv);
                testCase.verifyEqual(idx, c.expected_idx, "AbsTol", testCase.Tol, c.name);
            end
        end

        function coordImageToAtlas(testCase)
            cases = testCase.Cases.coord_image_to_atlas;
            for k = 1:numel(cases)
                c = cases(k);
                reg = testCase.regFor(c.project_file);
                [coords, inside] = reg.coord_image_to_atlas(string(c.slice), c.points, ...
                    "Space", string(c.space), "Units", string(c.units));
                testCase.verifyEqual(coords, c.expected_xyz, "AbsTol", testCase.Tol, c.name);
                testCase.verifyEqual(inside, logical(c.expected_inside), c.name);
            end
        end

        function coordAtlasToImage(testCase)
            cases = testCase.Cases.coord_atlas_to_image;
            for k = 1:numel(cases)
                c = cases(k);
                reg = testCase.regFor(c.project_file);
                res = reg.coord_atlas_to_image(c.xyz, ...
                    "Space", string(c.space), "Units", string(c.units));
                testCase.verifyEqual(res.section_id, string(c.expected_section_id), c.name);
                expValid = logical(c.expected_valid);
                testCase.verifyEqual(res.valid, expValid, c.name);
                % xy / distance are nan / inf where uncovered; the fixture stores
                % 0 there, so compare only the covered (valid) rows.
                if any(expValid)
                    testCase.verifyEqual(res.xy(expValid, :), c.expected_xy(expValid, :), ...
                        "AbsTol", testCase.Tol, c.name);
                    testCase.verifyEqual(res.distance(expValid), c.expected_distance(expValid), ...
                        "AbsTol", testCase.Tol, c.name);
                end
            end
        end
    end

    methods (Access = private)
        function checkWarp(testCase, cases, fn)
            for k = 1:numel(cases)
                c = cases(k);
                out = fn(c.points_norm, c.src_px, c.dst_px, c.work_w, c.work_h);
                testCase.verifyEqual(out, c.expected, "AbsTol", testCase.Tol, c.name);
            end
        end

        function reg = regFor(testCase, projectFile)
            % projectFile is stored relative to the fixtures directory.
            path = fullfile(testCase.FixturesDir, projectFile);
            reg = verso.VersoRegistration(string(path));
        end
    end
end
